version: '3'
services:
  backend:
    build: ./backend
    env_file: .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:80"
